# Generated by Django 3.2.5 on 2021-07-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patroller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=255)),
                ('armed', models.BooleanField(default=False)),
                ('cell', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WatchPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('alert', models.BooleanField(default=False)),
                ('full', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('patrollers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locator.patroller')),
                ('watch_point', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='locator.watchpoint')),
            ],
        ),
        migrations.AddField(
            model_name='patroller',
            name='current_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='locator.watchpoint'),
        ),
    ]
