# Generated by Django 3.2.5 on 2021-07-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_auto_20210716_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroller',
            name='code_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patroller',
            name='current_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locator.watchpoint'),
        ),
        migrations.AlterField(
            model_name='patroller',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patroller',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='patrollers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locator.patroller'),
        ),
        migrations.AlterField(
            model_name='watchpoint',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
