# Generated by Django 3.2.5 on 2021-07-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0004_auto_20210716_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='patroller',
            name='preferred_shifts',
            field=models.ManyToManyField(related_name='patroller_pref_shift', to='locator.Shift'),
        ),
        migrations.AddField(
            model_name='patroller',
            name='preferred_watchpoint',
            field=models.ManyToManyField(related_name='patroller_pref_point', to='locator.WatchPoint'),
        ),
    ]
