# Generated by Django 3.2.5 on 2021-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0005_auto_20210717_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroller',
            name='preferred_shifts',
            field=models.ManyToManyField(blank=True, null=True, related_name='patroller_pref_shift', to='locator.Shift'),
        ),
        migrations.AlterField(
            model_name='patroller',
            name='preferred_watchpoint',
            field=models.ManyToManyField(blank=True, null=True, related_name='patroller_pref_point', to='locator.WatchPoint'),
        ),
    ]
