# Generated by Django 3.2.5 on 2021-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0006_auto_20210717_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchpoint',
            name='abbreviation',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
