# Generated by Django 3.2.5 on 2021-07-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0008_auto_20210717_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locator.shift'),
        ),
        migrations.AlterField(
            model_name='team',
            name='watch_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locator.watchpoint'),
        ),
    ]
